# Generated by Django 5.1.3 on 2024-12-08 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_avaliacao_id_alter_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='num_produtos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
