# Generated by Django 5.1.3 on 2024-12-08 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_produto_num_produtos_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato (XX) XXXX-XXXX ou (XX) XXXXX-XXXX.', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')]),
        ),
    ]
